name: bracket_watch_local
services:
  bracket_watch_db:
    container_name: "bracket_watch_db"
    build:
      context: .. 
      dockerfile: src/BracketWatch.Data/db.Dockerfile
    ports:
      - "1433:1433"
  api:
    container_name: "bracket_watch_api"
    build:
      context: .. 
      dockerfile: src/BracketWatch.API/Dockerfile
      target: dev
    working_dir: /work
    volumes:
      - ../:/work
      - nuget:/root/.nuget/packages
    environment:
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: http://0.0.0.0:8080
    ports:
      - "8877:8080"

  bracket_watch_web:
    container_name: "bracket_watch_web"
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ../src/bracketwatch.frontend:/app
      - /app/node_modules
    environment:
      VITE_HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "1" 
    command: sh -c "npm ci || npm i && npm run dev -- --host --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  nuget: